#!/usr/bin/env python3

import os
import subprocess
import sys

import lib

def main():
    root = os.path.abspath(
        os.path.join(os.path.dirname(__file__), '..'))

    env = os.environ
    env.update({
        'GRPC_ENABLE_FORK_SUPPORT' : 'true',
    })

    server = subprocess.Popen(
        ['bin/be'],
        cwd=root)
    try:
        return subprocess.call(
            ['php', 'run_fork_test.php'],
            env=env, cwd=root)
    except KeyboardInterrupt:
        pass
    finally:
        server.kill()

if __name__ == '__main__':
    sys.exit(main())